# Generated by Django 4.2.1 on 2023-05-25 00:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0002_remove_trader_current_balance_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='trader',
            name='current_balance',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='trader',
            name='initial_balance',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.DeleteModel(
            name='Trade',
        ),
    ]
